### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by jenniferxgre** [AnAngryRaven/twitch-stats-remover-extension#17]
Hi, really appreciate the extension. It worked wonderfully until yesterday. Then it suddenly stopped working. 

I tested it on two different PCs on librewolf (firefox fork) and Chrome. Tried restarting the PC, changing settings, and reloading Twitch. But suddenly it does not hide any viewer or follower count at all. No clue at all what happened, if the error is on my side or on the extension's side. Wanted to report it in case more people are affected.

**Comment by AnAngryRaven** [comment]
Ok, I believe with exception to the stream together and title-mentioned users features (finding people using these are.. difficult) this should now be fixed!

Looks like AMO has already approved the new version, and Chrome Web Store should hopefully be some point soon(ish)

**Comment by jenniferxgre** [comment]
Thanks so much! However, seems like the hover one is still showing.

![Image](https://github.com/user-attachments/assets/718b26a4-da96-4323-9833-320cdae1b3ab)
